version: "3"

services:
  # https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#docker
  doc:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      URL: ""
      URLS: '[
        { "name": "[CDTN] Legal References API", "url": "https://cdtn-api.fabrique.social.gouv.fr" }
      ]'
    ports:
      - ${PORT}:8080
